apiVersion: apps/v1
kind: Deployment
metadata:
  name: awswebsitedeployment
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: awswebsite
        image: rsoftsysadmin/naveenaws
      imagePullSecrets:
         - name: regcred
