apiVersion: v1 
kind: Pod
metadata:
  name: awswebsite
  labels:
    app: webapp
spec:
  containers:
  - name: awswebsite
    image: rsoftsysadmin/naveenaws
    ports:
     - containerPort: 80
  imagePullSecrets:
  - name: regcred
    
   
