apiVersion: v1 
kind: Service
metadata:
  name: awswebsiteservice
  labels:
   app: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - port: 80
      nodePort: 31005
      targetPort: 80